### ISSUE TITLE
Code Structure

### ISSUE THREAD

**Issue by josephgupkim** [JacobHonore/Codecademy-Gather-TDD#2]
In terms of structure for the code that you've written, it seems to be organized and written in a legible manner. This means that your code is easy to navigate through having been written in the familiar pattern that is apparent throughout the lessons.

A great way to further increase the legibility of your code is to separate it into smaller portions and label with comments like in "user-visits-root-test.js". But because your code was already efficiently written, it's not a big deal that it was left out.

**Comment by JacobHonore** [comment]
Thank you. I will try to remember comments in next project.
